### PR TITLE
first argument of then method can't be optional

### PR DESCRIPTION
**Pull request by DavidBruant**

### CODE REVIEW

**Comment by domenic** [comment]
Why?

**Comment by DavidBruant** [comment]
`somePromise.then()` is just creating a new Future which is no different than the previous one. Most likely an error case, no?

**Comment by domenic** [comment]
It allows programmer flexibility:

``` js
somePromise.then(condition ? undefined : onFulfilled, onRejected)
```

**Comment by DavidBruant** [comment]
Arguably, it's expressed more clearly with

``` js
if(condition)
  somePromise.catch(onRejected)
else
  somePromise.then(onFulfilled, onRejected)
```

Feel free to close the PR if you disagree.

**Comment by slightlyoff** [comment]
I don't know that the restriction buys us much. Closing, sorry.

**Comment by DavidBruant** [comment]
Don't be sorry, I made a case, I understand others can disagree. That's not a very important point either.
I've listed the points I really care about [elsewhere](http://lists.w3.org/Archives/Public/public-sysapps/2013Feb/0120.html) if you (or anyone else) is interested.

**Comment by slightlyoff** [comment]
Thanks! I think `DOMRequest` needs to go...at a minimum, we need to re-describe it in terms of `EventedFuture`. That way we can just fight about the semantics in one place = )

**Pull request closed without merging**
