### PR TITLE
Add support for asynchronous iterator using a Cursor interface

### PR DESCRIPTION
**Pull request by sicking**
This is just a first draft for cursor support. Changes are definitely needed. See "issues" list for further thoughts.

### CODE REVIEW

**Comment by mounirlamouri** [comment]
I'm not a big fan of the .each(), .whenFinished() and .whenNext() and .next() methods.

Basically, I believe we could have everything living around .forEach() if we design .forEach() differently.

I propose to have:

``` idl
callback CursorCallback = Future (any value);
Future forEach(CursorCallback callback);
```

That way, the next element of a cursor can be fetch ASAP or when a Future is resolved:

``` javascript
cursor.forEach(function(v) {
  doSomething(v); // get the next item ASAP
})
cursor.forEach(function(v) {
  return doSomethingAsync(v); // get the next item when the returned Future is done
});
```

I believe that this design deprecates .whenFinished(), .whenNext(), .each() and .next() and would make .forEach() behaves like .then() but chaining with itself.

Also, I wonder if .stop() wouldn't be better than .continue(). I think a complex code flow would be much easier to read if the exception was clearly marked instead of the common case. When getting a Cursor, fetching the next item seems a pretty common action while stopping the cursor will happen only once in the cursor life time. Using .stop() would be less error-prone and more readable. Also, .continue() should be considered as explicitly called by the Future when it is returned. A good example would be something like:

``` javascript
cursor.forEach(function(v) {
  var v = gettingSomeState(v);
  switch (v) {
    case 1:
      return doAsync();
    case  2:
      doThat();
      break;
    case 3:
      return anotherAsync();
    case 4:
      somethingElse();
      break;
    case 5:
      cleanUp();
      this.stop();
  }
});
```

**Comment by domenic** [comment]
+1 to

``` js
cursor.forEach(function(v) {
  doSomething(v); // get the next item ASAP
})
cursor.forEach(function(v) {
  return doSomethingAsync(v); // get the next item when the returned Future is done
});
```

The first thing I thought when scrolling through the proposal was that introducing `self.continue()` was a very un-promisey way of doing this sort of thing.

**Comment by wycats** [comment]
I don't think that an async `forEach` is appropriate. It's already in wide use for sync iterators and people will not expect the async behavior.

**Comment by sicking** [comment]
I really like the idea of having the `forEach` callback (or whatever we call it) be able to return a Future in order to pause the Cursor until the Future is resolved. That will allow using `forEach` in many more situations rather than having to use `continue`. For example the following would work great:

``` javascript
var sum = 0;
getItemsAsCursor().forEach(function(id) {
  return getValueForId(id).then(function(v) {
    sum += v;
  });
})
```

But I still think `continue` is a better solution in a few cases. The most obvious one is if you are getting a cursor but only want the first 10 items. It seems very awkward and hacky to after the 10th item return a Future which is never resolved.

Similarly, consider if you create a paged UI which renders 10 items at a time, and which has a "next" button for rendering the next 10 items.
- With the current proposal, when the "next" button is pressed you call `cursor.continue()`.
- If we just had the ability to pause the Cursor using a returned Future, you have to create a Future, grab the created ResolverCallbacks, and then call `resolver.accept()`.

Simply calling `cursor.continue()` seems smoother?

Additionally we still need the `.each()` function in order to have the ability to have multiple consumers of the value stream from a Cursor. Should we allow all callbacks registered through `.each` to return a Future in order to pause the cursor?

**Comment by sicking** [comment]
Another case where `.continue()` seems like a better solution than the alternatives is for supporting "joins" between multiple cursors. Consider for example

``` javascript
c1 = getCursor1();
c2 = getCursor2();
intersection = [];
function findIntersection() {
  if (c1.status === "pending" || c2.status === "pending") {
    // This will only happen during the first call to findIntersection
    // before both cursors have loaded a value
    return;
  }
  if (c1.value === c2.value) {
    intersection.push(c1.value);
    c1.continue();
  }
  else if (c1.value < c2.value) {
    c1.continue();
  }
  else {
    c2.continue();
  }
}
c1.each(findIntersection);
c2.each(findIntersection);
c1.whenFinished().then(displayResult.bind(null, intersection));
c2.whenFinished().then(displayResult.bind(null, intersection));
```

This is pretty ugly, but I trying to use .forEach and pausing cursors using Futures gets much worse.

Definitely interested to see if we can find better ways of solving this pattern though.

**Comment by sicking** [comment]
I wonder if it would help to add a function like:

``` javascript
forEachUntil: function(callback) {
  this.continue();
  let self = this;
  return new Future(function(r) {
    function handler(cursor_value) {
      if (self.state === "finished") {
        r.accept(false);
      }
      let res = callback.call(self, cursor_value);
      if (Future.isFuture(res)) {
        res.then(hasRes);
      } else {
        hasRes(res);
      }
      function hasRes(foundMatch) {
        if (foundMatch) {
          r.accept(true);
        } else {
          self.whenNext().then(handler);
        }
      }
    }
    self.whenNext().then(handler);
    self.whenFinished().catch(function(err) {
      r.reject(err);
    }
  });
}
```

I.e. `forEachUntil` is like `forEach` except that it synchronously or asynchronously returns a boolean value indicating if the cursor should keep going or not. The `forEachUntil` function returns a Future which is resolved once `true` is returned or once the end of the cursor is reached.

The above code is untested and probably contains bugs. But I hope it gets the idea across.

**Comment by DavidBruant** [comment]
When I read the [goals](https://github.com/sicking/DOMFuture/blob/ad17415393f9ffc21bd10248af8286c9f1e1d1d2/Cursor.idl#L6-L21), this proposal smells a lot like a subset of [Node's Readable interface](http://nodejs.org/docs/v0.10.0/api/stream.html#stream_class_stream_readable). This API grew out of the **several years** of experience with streams in Node (they are even [giving talks](http://www.youtube.com/watch?v=tgTniHwGPuM&feature=share&list=PLMW8Xq7bXrG77SV1VAAiAciRyq3VSC2Gq) (sorry, this talk is also about other things than streams and streams are discussed at different points of the video) about their experience and the relevant modifications at the API level).
On the "cursor" aspect, the ReadableStream API has an "object mode" which would be relevant for async iteration over something like a bunch of SMS, etc.

I feel the use cases, especially this part:

> // The API is intended to provide both the ability to read the full data
> // stream, or read data up until the point that the consumer is interested.

are converging (the video talks about a previous version of the stream API where when you wanted 4 bytes of of a stream, it was pretty annoying that Node was giving you all had and the new API takes care of that) and we'd probably save a lot of time to design a cursor API by shaving off what we don't need and adapt from [Node's Readable](http://nodejs.org/docs/v0.10.0/api/stream.html#stream_class_stream_readable) rather than restarting from scratch.

What do you all think?

**Comment by domenic** [comment]
+1 to @DavidBruant. I think promises are not always a great interface for streaming stuff. Although, I will mention that @kriskowal has spent some time figuring out ways to merge the paradigms in his projects. Similarly @mattpodwysocki might have thoughts.

**Comment by sicking** [comment]
@DavidBruant yes, definitely sounds like the Readable interface in "object mode" has similar goals as the Cursor proposed here. Though I wasn't able to really find much information about the "object mode".

However the Readable interface doesn't seem to integrate with promises at all. This is certainly a fine design decision, but just runs contrary to what I was trying to accomplish here. In particular I was hoping to be able to convert IndexedDB to be designed around Futures, which means that we have to find a solution for how to deal with enumeration.

**Comment by tabatkins** [comment]
Woo, thread necro!

I really don't like this design.  I like the goals, don't get me wrong, but the way it's presented is troublesome - it's very imperative, where you just consume a cursor and that's it.  There's no pass-through, like there is for Futures, where you can take a cursor, manipulate it, and something else can operate on the manipulated cursor, allowing you to chain operations nicely.  I think this is a necessary quality of any proper solution to this kind of problem.

Also, there are multiple distinct, but related, use-cases for this kind of asynchronous "multi-Future".  One is what you've outlined in the Cursor design, where you just want an iterator, but asynchronous.  In particular, if you're in control of the cursor, you can't miss any updates, because it buffers values automatically, and you control when it emits its next value.

Another is where you don't want this buffering - you just want events, but with all the wonderful benefits that come from making asynchrony a first-class property of the object, a la Futures.  No consumer controls the emitting, and it's possible to miss events if you register too late, but it's efficient and simple.  I cover this in my proposal for EventStream at http://www.xanthir.com/b4PV0.

A third is where you want a _reactive value_, or an attribute++.  You can just read its value normally, but you can also register a callback for updates.  This is very close to the events case, but there are subtle things that make it distinct: if you're processing all values, you probably want the current value too, so it's useful to have the mapping function immediately call its callback with the current value; if the value updates once, and then while your callback is in the queue waiting to be processed, it updates again, you probably want your callback called only once, with the latest value, rather than having it called with the old value and then again with the new value (causing you to possibly do useless work on stale data, or have to always check the actual value object to see if the value is stale or not).  I cover this in my proposal for ValueStream in the blog post linked above, though I think it could use a better name to differentiate it more from EventStream.

All three of these benefit from the composition/chaining I talked about, where you can manipulate a stream and then register callbacks on the manipulated stream rather than the original.  There are some examples in and linked from my blog post.

I'm really excited to help develop something like this, though!  You probably already know that @slightlyoff started a repo at https://github.com/slightlyoff/Stream/ to track it.

**Comment by mounirlamouri** [comment]
> I'm really excited to help develop something like this, though! You probably already know that @slightlyoff started 
> a repo at https://github.com/slightlyoff/Stream/ to track it.

I guess this is private?

**Comment by mattpodwysocki** [comment]
@tabatkins 
I would love to see the Stream repo as it seems to be private.  I have quite a bit of thoughts on manipulating streams given my work on the Reactive Extensions for JavaScript and other versions including .NET, C++, Ruby, etc.  
https://github.com/Reactive-Extensions/RxJS

We have a simple set of requirements for our design:
- Observable and Observer "interfaces"
  1. An Observer - aka Receiver of data, being pushed to it
  2. An Observable Sequence - aka Sender of data
-  Functional style composition to enable:
  1. Creation of sequences via range, repeat, create, from array, single value, empty, etc
  2. Standard query operators such as map, filter, scan, take, skip, selectMany/concatMap to compose
  3. Time-based operators such as throttle, generate over time, time stamping, timers, timeouts
  4. Coincidence operators such as groupJoin, join, windowing and buffering
  5. Aggregation operators such as reduce, count, some, every
  6. Error handling operators such as catch, throw, onErrorResumeNext, retry
  7. [Join Calculus](http://en.wikipedia.org/wiki/Join-calculus)
- Schedulers to control concurrency, to use the best async or sync scheduling mechanism based upon the job required.  This also controls when and how the queries are executed.

The overall structure of the Observer class is:

``` js
Observer = {
    onNext: (T) => ()
    onError: (TError) => ()
    onCompleted: () => ()
}
```

The structure for the Observable sequence is very simple as well:

``` js
Observable = {
    subscribe: (Observer) => Disposable
}

// Used for cleaning up resources such as event handles, file handles, etc
Disposable = {
    dispose: () => ()
}
```

We also enforce a specific grammar in which:
- onNext (0 ... N) times
- Optional onError(1) or onCompleted (1)

After an onError or onCompleted calls are fired, no others can fire and the sequence has been terminated.  In the case of standard Event streams, you will get 0 to N calls of onNext with no onCompleted nor onError.  In the case of a promise-like operation such as our AsyncSubject (an Observer and Observable) you get one onNext value and an onCompleted call where the value is then cached for all subsequent calls.

This pattern has worked out for us well as has served as the inspiration for Dart Streams:
http://news.dartlang.org/2012/11/introducing-new-streams-api.html

In fact, I'd like to take that discussion forward to even talk about first-class events as a whole

Matt

**Comment by DavidBruant** [comment]
> In fact, I'd like to take that discussion forward to even talk about first-class events as a whole

<3 :+1: +1 Let's do that at the ECMAScript level for ES7.

**Comment by tabatkins** [comment]
Agreed!

@mattpodwysocki Check my blog post at http://www.xanthir.com/b4PV0 for my current exploration of the topic of streams/reactive values.

**Comment by neonstalwart** [comment]
given the talk of streams (:+1:) i'm not sure if the original proposal here is still under consideration but it sounds like what was described as the async `forEach` might be better named `reduce` (or maybe `fold` where the current value is passed as the first argument to the iterator function) where the `prev` passed to the iterator is the resolved value of the accumulated value.

``` js
cursor.forEach(function(v) {
  doSomething(v); // get the next item ASAP
});
cursor.reduce(function(prev, v) {
  return doSomethingAsync(v); // get the next item when the returned Future is done
});
```

**Comment by mattpodwysocki** [comment]
@neonstalwart I'd prefer instead of foreach, subscribe which is covered in most of the "stream" libraries such as Knockout.js, RxJS, Bacon.js and so forth.  Foreach at least to me describes blocking behavior whereas subscribe implies pushing behavior.  

To me, reduce implies that you have that you have a final value at the end which is not the case with forEach as it is a void operation.  If you truly want reduce like behavior on a stream, then I'd recommend a name like scan, which we have a rolling aggregation where you receive incremental values.

``` js
// Implies blocking
someSequence.forEach(onNextHandler);

// Implies non-blocking
someStream.subscribe(
    onNextHandler,
    onErrorHandler,
    onCompletionHandler
);
```

The subscribe here implies that you can handle not only the next values that come back, but also completion and error handling which don't mean as much in the blocking behavior world.

**Comment by neonstalwart** [comment]
@mattpodwysocki i like the stream abstraction - my comment was meant to be unrelated to streams though

> given the talk of streams (:+1:) i'm not sure if the original proposal here is still under consideration but...

streams would probably make my comment (and maybe the original proposal here) moot.

**Comment by tabatkins** [comment]
Following up on this (thread necro again, yay!), I think something like this is a good idea, just not the only idea.  As an asynchronous iterator, this has approximately the right shape, though there's good discussion in this thread about how to tweak things better.  It doesn't solve all the stream-based use-cases, but it doesn't need to.

**Pull request closed without merging**
